bump_version: null
lint: null
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Ben Southgate, James Ashmore
  description: Alternative splicing analysis using RNA-seq.
  force: false
  is_nfcore: true
  name: rnasplice
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.5
update: null