name: nf-core AWS full size tests
# This workflow is triggered on published releases.
# It can be additionally triggered manually with GitHub actions workflow dispatch button.
# It runs the -profile 'test_full' on AWS batch

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  run-tower:
    name: Run AWS full tests
    if: github.repository == 'nf-core/rnasplice'
    runs-on: ubuntu-latest
    steps:
      - name: Launch workflow via tower
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          revision: ${{ github.sha }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/rnasplice/work-${{ github.sha }}
          parameters: |
            {
              "hook_url": "${{ secrets.MEGATESTS_ALERTS_SLACK_HOOK_URL }}",
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/rnasplice/results-${{ github.sha }}"
            }
          profiles: test_full
      - uses: actions/upload-artifact@v4
        with:
          name: tower_action_*.{log,json}
          path: |
            tower_action_*.{log,json}
            
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: Tower debug log file
          pattern: tower_action_*.{log,json}